name: Build Project J.A.R.V.I.S.

on:
  push:
    branches: [ "main" ] # Runs whenever you update the main branch
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # This step is a failsafe. If gradlew is missing, the next step will use the cached gradle.
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Project-JARVIS-apk
          path: app/build/outputs/apk/debug/app-debug.apk
